<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Nagendra-Yoga" name="com.DollarDays.testCases.HomePageAfterSigninTest" tests="4" failures="1" timestamp="2021-08-26T15:17:44 PDT" time="24.263" errors="0">
  <testcase name="TC_Login" time="24.263" classname="com.DollarDays.testCases.HomePageAfterSigninTest">
    <failure type="java.lang.AssertionError" message="Could not Login to Dollardays.Testcase failed. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Could not Login to Dollardays.Testcase failed. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at com.DollarDays.testCases.HomePageAfterSigninTest.TC_Login(HomePageAfterSigninTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_Login -->
  <system-out/>
  <testcase name="TC_verifyUserHomePageTitle" time="0.000" classname="com.DollarDays.testCases.HomePageAfterSigninTest">
    <skipped/>
  </testcase> <!-- TC_verifyUserHomePageTitle -->
  <system-out/>
  <testcase name="TC_CheckUserDropDownList" time="0.000" classname="com.DollarDays.testCases.HomePageAfterSigninTest">
    <skipped/>
  </testcase> <!-- TC_CheckUserDropDownList -->
  <system-out/>
  <testcase name="TC_verifyUserDropDownUrl" time="0.000" classname="com.DollarDays.testCases.HomePageAfterSigninTest">
    <skipped/>
  </testcase> <!-- TC_verifyUserDropDownUrl -->
  <system-out/>
</testsuite> <!-- com.DollarDays.testCases.HomePageAfterSigninTest -->
